wulkanowy/wulkanowy

api/build.gradle
Downgrade to prev version
see https://github.com/jhy/jsoup/issues/992
=> Hotfix jsoup issue

app/src/main/res/layout/activity_login.xml
https://stackoverflow.com/a/47955385/6695449
=> Fix autofill on API level 26

.github/ISSUE_TEMPLATE.md
Should help with new user mess.
=> Created issue template

app/src/main/res/values/strings.xml
Change `timetable_no_items` from `No lesson in this day` to `No lessons on this day`
Change `widget_timetable_no_items` from `No lesson` to `No lessons`
Change `pref_services_wifi` from `Only WiFi` to `Wi-Fi only`
=> English translation fix

app/src/main/res/values/strings.xml
Changed `exam_no_items` from **No exams in this week** to **No exams on this week**
=> Fix exam_no_items english translation

app/src/main/res/drawable/ic_menu_grade_semester_24dp.xml
https://materialdesignicons.com/icon/calendar-multiple
=> Change icon of semester switch

app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/LuckyNumberFragment.kt
=> Fix lucky number crash

app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt, app/src/main/res/values/api_endpoints.xml, app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
=> Fill login credentials with default values upon fakelog selection

app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
Update invalid password message from `This password is incorrect` (`To hasło jest niepoprawne`) to `Login details are incorrect` (`Dane logowania są niepoprawne`)
=> Update login error message

app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
Update settings view section name from `View` (`Widok`) to `Appearance` (`Wygląd`)
close #261
=> Settings rename view section

.travis.yml, app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt, app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentLocal.kt
=> Fix more than one current student

app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration13.kt, app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageLocal.kt, app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRemote.kt, app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt
=> Fix message loading if student and parent are logged in

app/src/main/res/layout/item_login_student_select.xml
Improve login student selection layout to better match Material guidelines
=> Improve login student selection layout

app/src/main/java/io/github/wulkanowy/services/sync/SyncManager.kt
=> Fix network constraint in background sync

app/build.gradle, app/schemas/io.github.wulkanowy.data.db.AppDatabase/14.json, app/src/androidTest/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt, app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/GradeSummary.kt, app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration14.kt, app/src/main/java/io/github/wulkanowy/data/repositories/gradessummary/GradeSummaryRemote.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryItem.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt, app/src/main/res/layout/item_grade_summary.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt, app/src/test/java/io/github/wulkanowy/utils/GradeExtensionTest.kt
https://github.com/wulkanowy/api/commit/9afd60b224ae1fbd9153ce5666ecdd4b99f8250e
=> Show grades average from register if exist instead of calculating

app/src/main/res/values-pl/strings.xml
Change `about_feedback_summary` from `Wyślij zgłoszenie o błedzię poprzez e-maila` to `Wyślij zgłoszenie o błędzie poprzez e-maila`
=> Fix about_feedback_summary PL typo

app/src/main/java/io/github/wulkanowy/ui/modules/mobiledevice/token/MobileDeviceTokenDialog.kt
=> Add click to copy function

app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryFragment.kt
=> Fix duplicate percentage in attendance summary

app/build.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt, app/src/main/res/layout/fragment_attendance_summary.xml, app/src/main/res/values/api_endpoints.xml, app/src/main/res/values/api_hosts.xml
=> Add support for edu.lublin.eu

app/build.gradle, app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt, app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt, app/src/main/java/io/github/wulkanowy/di/AppModule.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/school/SchoolFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsView.kt, app/src/main/java/io/github/wulkanowy/utils/AppInfo.kt, app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt, app/src/main/res/values-pl/preferences_values.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/preferences_defaults.xml, app/src/main/res/values/preferences_keys.xml, app/src/main/res/values/preferences_values.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/scheme_preferences.xml
=> Add language change settings

README.en.md, README.md, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/preferences_values.xml, app/src/main/res/values/strings.xml
In this fork I've made small changes to strings in the resources and in the readme to make them sound better (which is completely subjective but I'm willing to explain every change) or, in the case of readme, to reflect recent additions to the application.
=> Minor translation changes

app/jacoco.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsDialog.kt, app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt, app/src/main/res/layout/dialog_grade.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
=> Improve grades dialog layout

app/src/main/res/layout/fragment_login_advanced.xml, app/src/main/res/layout/fragment_login_form.xml
Fix login info autofill
Tested on:
- LastPass
- Google Password Manager
- Keepass2Android
=> Fix login info autofill

app/build.gradle, app/schemas/io.github.wulkanowy.data.db.AppDatabase/20.json, app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TestTimetableEntityCreator.kt, app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/Timetable.kt, app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration20.kt, app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemote.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableItem.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt, app/src/main/res/layout/item_timetable_small.xml, app/src/main/res/values-pl/preferences_values.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/preferences_values.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/preferences_defaults.xml, app/src/main/res/values/preferences_keys.xml, app/src/main/res/values/preferences_values.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/scheme_preferences.xml
=> Add option to show only student plan lessons

app/src/main/res/layout/fragment_login_advanced.xml, app/src/main/res/layout/fragment_login_form.xml
=> Don't hide password toggle button on error

app/build.gradle, app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration20.kt, app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocal.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt, app/src/main/java/io/github/wulkanowy/utils/NumberExtension.kt
=> Visual enhancement of displaying grades point stats

app/src/main/res/layout/fragment_login_form.xml
=> Fix login more options button in dark theme

app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryItem.kt, app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryView.kt, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml
=> Add total attendance summary

app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectItem.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt, app/src/main/res/layout/item_login_student_select.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
=> Disable signed in students in login

app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt, app/src/main/res/layout/fragment_login_advanced.xml, app/src/main/res/layout/fragment_login_form.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/api_hosts.xml, app/src/main/res/values/strings.xml, app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
Add dynamic changing of name field hint in login form and advanced login based on selected register
=> Add dynamic nick/email in login

app/src/androidTest/java/io/github/wulkanowy/data/repositories/timetable/TestTimetableEntityCreator.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/Timetable.kt, app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemote.kt, app/src/main/java/io/github/wulkanowy/services/widgets/TimetableWidgetService.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableItem.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt, app/src/main/res/layout/item_widget_timetable_small.xml, app/src/main/res/layout/item_widget_timetable_small_dark.xml
=> Respect user settings in timetable app widget

app/build.gradle, app/src/fdroid/java/io/github/wulkanowy/utils/CrashlyticsUtils.kt, app/src/main/AndroidManifest.xml, app/src/main/java/io/github/wulkanowy/WulkanowyApp.kt, app/src/main/java/io/github/wulkanowy/data/repositories/logger/LoggerRepository.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/logviewer/LogViewerView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt, app/src/main/java/io/github/wulkanowy/utils/LoggerUtils.kt, app/src/main/res/drawable/ic_refresh.xml, app/src/main/res/layout/fragment_logviewer.xml, app/src/main/res/layout/item_logviewer.xml, app/src/main/res/menu/action_menu_logviewer.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/provider_paths.xml, app/src/play/java/io/github/wulkanowy/utils/CrashlyticsUtils.kt
=> Add log viewer

app/src/androidTest/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocalTest.kt, app/src/main/java/io/github/wulkanowy/data/db/dao/GradePointsStatisticsDao.kt, app/src/main/java/io/github/wulkanowy/data/pojos/GradeStatisticsItem.kt, app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsLocal.kt, app/src/main/java/io/github/wulkanowy/data/repositories/gradestatistics/GradeStatisticsRepository.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsView.kt, app/src/main/java/io/github/wulkanowy/utils/NumberExtension.kt, app/src/main/res/layout/fragment_grade_statistics.xml, app/src/main/res/layout/item_grade_statistics_bar.xml, app/src/main/res/layout/item_grade_statistics_pie.xml
=> Show list of charts in grade statistics

app/src/androidTest/java/io/github/wulkanowy/data/repositories/grade/GradeRepositoryTest.kt, app/src/main/java/io/github/wulkanowy/data/db/dao/MessagesDao.kt, app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageLocal.kt, app/src/main/java/io/github/wulkanowy/data/repositories/message/MessageRepository.kt, app/src/test/java/io/github/wulkanowy/data/repositories/UnitTestInternetObservingStrategy.kt, app/src/test/java/io/github/wulkanowy/data/repositories/message/MessageRepositoryTest.kt, app/src/test/java/io/github/wulkanowy/data/repositories/student/StudentRemoteTest.kt
=> Replace Maybe with Single in Message DAO

app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigureActivity.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureActivity.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/strings.xml
=> Add "System theme" option to widgets

app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigureActivity.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureActivity.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/strings.xml
Reverts wulkanowy/wulkanowy#739
=> Revert "Add "System theme" option to widgets"

app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt, app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt, app/src/main/java/io/github/wulkanowy/ui/modules/main/MainModule.kt, app/src/main/java/io/github/wulkanowy/utils/ResourcesExtension.kt, app/src/main/res/layout/dialog_error.xml, app/src/main/res/values-pl/strings.xml
=> Add error message and bug report button to error dialog

app/src/main/java/io/github/wulkanowy/data/repositories/semester/SemesterRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/student/StudentLocal.kt, app/src/test/java/io/github/wulkanowy/data/repositories/semester/SemesterRepositoryTest.kt
=> Refresh semesters if previous list was downloaded in different mode

app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/homework/details/HomeworkDetailsDialog.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt, app/src/main/res/drawable/ic_fullscreen.xml, app/src/main/res/drawable/ic_fullscreen_exit.xml, app/src/main/res/layout/item_homework_dialog_details.xml
=> Add fullscreen mode to homework dialog

app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt, app/src/main/res/layout/fragment_grade_statistics.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/preferences_defaults.xml, app/src/main/res/values/preferences_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/scheme_preferences.xml
=> Add option to hide/show chart list in grade class stats

app/src/main/AndroidManifest.xml, app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabView.kt, app/src/main/res/drawable/ic_search.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/menu/action_menu_message_tab.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
=> Add search in messages

app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt
=> Fix grade sorting

app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
=> Fix mark message as read in search mode

app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
=> Add debug statements to get/update methods in grade details adapter

app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
=> Fix crash in timetable time left

app/build.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverFragment.kt
=> Destroy webview in password recover before setting binding to null

app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutView.kt, app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/strings.xml
=> Show `check for updates` dialog before report a bug

app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationSchedulerHelper.kt
https://stackoverflow.com/a/29703161/6695449
=> Fix too many alarms on samsung devices

build.gradle
Reverts wulkanowy/wulkanowy#853
=> Revert "Bump sonarqube-gradle-plugin from 2.8 to 3.0"

app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt, app/src/main/res/layout/fragment_login_student_select.xml
=> Fix login button state in student select login fragment

app/schemas/io.github.wulkanowy.data.db.AppDatabase/25.json, app/schemas/io.github.wulkanowy.data.db.AppDatabase/26.json, app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/GradeSummary.kt, app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration26.kt, app/src/main/java/io/github/wulkanowy/data/repositories/grade/GradeLocal.kt, app/src/main/java/io/github/wulkanowy/data/repositories/grade/GradeRepository.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/GradeWork.kt, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
=> Add predicted and final grade notifications

app/src/main/java/io/github/wulkanowy/ui/base/BasePresenter.kt
=> Fix crash in flowWithResourceIn()

app/src/main/java/io/github/wulkanowy/data/repositories/preferences/PreferencesRepository.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/preferences_defaults.xml, app/src/main/res/values/preferences_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/scheme_preferences.xml
=> Show subjects without grades in "Grades"

app/src/main/java/io/github/wulkanowy/services/sync/works/NoteWork.kt, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml
=> Different notification for notes and praises

app/build.gradle, app/src/main/java/io/github/wulkanowy/data/db/adapters/PairAdapterFactory.kt, app/src/test/java/io/github/wulkanowy/data/db/ConvertersTest.kt
=> Fix string pair list type converter

app/src/main/java/io/github/wulkanowy/services/alarm/TimetableNotificationSchedulerHelper.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
=> Cancel scheduled lesson notifications which turned into canceled

app/build.gradle, app/src/main/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemote.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt, app/src/main/res/values/api_hosts.xml, app/src/test/java/io/github/wulkanowy/data/repositories/timetable/TimetableRemoteTest.kt
=> Add register variant auto-matching based on email

app/build.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
=>  Fix username label on registers other than default 

app/build.gradle
=> Use work-gcm dependency in play flavor only

app/src/main/AndroidManifest.xml, app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashActivity.kt, app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/splash/SplashView.kt, app/src/test/java/io/github/wulkanowy/ui/modules/splash/SplashPresenterTest.kt
=> Handle URLs from FCM push notification

app/src/main/java/io/github/wulkanowy/data/db/dao/MobileDeviceDao.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/MobileDevice.kt, app/src/main/java/io/github/wulkanowy/data/mappers/MobileDeviceMapper.kt, app/src/main/java/io/github/wulkanowy/data/repositories/MobileDeviceRepository.kt
=> Use userLoginId to differentiate saved mobiles devices between accounts 

app/src/main/java/io/github/wulkanowy/data/db/dao/RecipientDao.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/Recipient.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/ReportingUnit.kt, app/src/main/java/io/github/wulkanowy/data/mappers/RecipientMapper.kt, app/src/main/java/io/github/wulkanowy/data/mappers/ReportingUnitMapper.kt, app/src/main/java/io/github/wulkanowy/data/repositories/RecipientRepository.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/RecipientWork.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt, app/src/test/java/io/github/wulkanowy/data/repositories/RecipientLocalTest.kt
=> Use senderId to differentiate saved recipients between accounts

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt, app/src/main/java/io/github/wulkanowy/utils/AppInfo.kt
=> Add build date to version info 

app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
=> Fix empty messages after timeout bug

app/build.gradle
Reverts wulkanowy/wulkanowy#1138
=> Revert "Bump fragment-ktx from 1.2.5 to 1.3.0"

app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/AttendanceSummaryRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/ConferenceRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/GradeRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/HomeworkRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/LuckyNumberRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/MobileDeviceRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/NoteRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/SchoolRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/StudentInfoRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/SubjectRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/TeacherRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/TimetableRepository.kt, app/src/main/java/io/github/wulkanowy/utils/FlowUtils.kt, app/src/test/java/io/github/wulkanowy/data/repositories/AttendanceRepositoryTest.kt, app/src/test/java/io/github/wulkanowy/data/repositories/CompletedLessonsRepositoryTest.kt, app/src/test/java/io/github/wulkanowy/data/repositories/ExamRemoteTest.kt, app/src/test/java/io/github/wulkanowy/data/repositories/GradeRepositoryTest.kt, app/src/test/java/io/github/wulkanowy/data/repositories/LuckyNumberRemoteTest.kt, app/src/test/java/io/github/wulkanowy/data/repositories/MobileDeviceRepositoryTest.kt, app/src/test/java/io/github/wulkanowy/utils/FlowUtilsKtTest.kt
=> Fix duplicate items after running automatic and manual sync at the same time 

app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
=> Fix empty view in attendance

app/src/main/java/io/github/wulkanowy/ui/base/WidgetConfigureAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigureActivity.kt, app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigurePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/luckynumberwidget/LuckyNumberWidgetConfigureView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureActivity.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigurePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetConfigureView.kt, app/src/main/res/values-night/styles.xml, app/src/main/res/values/styles.xml
=> Fix colorPrimary and class name in widget account manager

app/src/main/java/io/github/wulkanowy/data/db/dao/RecipientDao.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/Recipient.kt, app/src/main/java/io/github/wulkanowy/data/mappers/RecipientMapper.kt, app/src/main/java/io/github/wulkanowy/data/mappers/ReportingUnitMapper.kt, app/src/main/java/io/github/wulkanowy/data/repositories/RecipientRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/ReportingUnitRepository.kt, app/src/test/java/io/github/wulkanowy/data/repositories/RecipientLocalTest.kt
=> Use db student id to distinguish reporting units and recipients

.github/workflows/test.yml, app/build.gradle, build.gradle
=> Add deploy to AppGallery github actions config

app/build.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt, app/src/main/java/io/github/wulkanowy/ui/widgets/SwipeDisabledViewPager.kt, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml, app/src/main/res/xml/identificators.xml
=> Migrate to Google bottom navigation

.gitignore, app/src/main/java/io/github/wulkanowy/ui/modules/note/NotePresenter.kt
=> Fix sorting notes in loading state

README.en.md, README.md, app/src/main/java/io/github/wulkanowy/data/pojos/Notification.kt, app/src/main/java/io/github/wulkanowy/services/sync/channels/LuckyNumberChannel.kt, app/src/main/java/io/github/wulkanowy/services/sync/channels/NewConferencesChannel.kt, app/src/main/java/io/github/wulkanowy/services/sync/channels/NewExamChannel.kt, app/src/main/java/io/github/wulkanowy/services/sync/channels/NewGradesChannel.kt, app/src/main/java/io/github/wulkanowy/services/sync/channels/NewHomeworkChannel.kt, app/src/main/java/io/github/wulkanowy/services/sync/channels/NewMessagesChannel.kt, app/src/main/java/io/github/wulkanowy/services/sync/channels/NewNotesChannel.kt, app/src/main/java/io/github/wulkanowy/services/sync/channels/NewSchoolAnnouncementsChannel.kt, app/src/main/java/io/github/wulkanowy/services/sync/notifications/BaseNotification.kt, app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewConferenceNotification.kt, app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewExamNotification.kt, app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewGradeNotification.kt, app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewHomeworkNotification.kt, app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewLuckyNumberNotification.kt, app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewMessageNotification.kt, app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewNoteNotification.kt, app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewSchoolAnnouncementNotification.kt, app/src/main/java/io/github/wulkanowy/services/sync/notifications/NotificationType.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/ConferenceWork.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/ExamWork.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/GradeWork.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/HomeworkWork.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/LuckyNumberWork.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/MessageWork.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/NoteWork.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/SchoolAnnouncementWork.kt, app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/NotificationDebugPresenter.kt
=>  Add student nick-or-name to notification summary 

app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
=> Fix filter search bug

app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
=> Fix buggy timers in timetable

app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryAdapter.kt, app/src/main/res/layout/scrollable_header_grade_summary.xml, app/src/main/res/values/strings.xml
=> Add captions for averages from how many items have been counted

app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
=> Hide keyboard on opening login host dropdown

app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/history/LuckyNumberHistoryFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/luckynumber/history/LuckyNumberHistoryPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
=> Fix crash on opening date pickers during holidays 

app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt
Ref https://twitter.com/cketti/status/1294623423231070214
=> Fix opening twitter link from about on android 11

app/build.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
Fixes #1471
Bug introduced in #1428
=> Fix showing error view in timetable

app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementDialog.kt, app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt, app/src/main/res/layout/dialog_school_announcement.xml
=>  Add missing school announcement dialog 

app/src/main/java/io/github/wulkanowy/data/repositories/GradeRepository.kt, app/src/main/java/io/github/wulkanowy/data/repositories/SemesterRepository.kt, app/src/main/java/io/github/wulkanowy/ui/base/BasePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardItem.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt, app/src/main/java/io/github/wulkanowy/utils/FlowUtils.kt, app/src/main/java/io/github/wulkanowy/utils/TimetableExtension.kt, app/src/main/res/layout/item_dashboard_horizontal_group.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/io/github/wulkanowy/utils/TimetableExtensionTest.kt
=> Dashboard fixes

app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
=> Fix overlapping error view

app/src/main/java/io/github/wulkanowy/ui/modules/attendance/summary/AttendanceSummaryPresenter.kt
=> Fix error view in attendance summary

app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceDialog.kt, app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferencePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/conference/ConferenceView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementDialog.kt, app/src/main/res/layout/dialog_conference.xml, app/src/main/res/values/strings.xml
=> Add conference dialog

app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt, app/src/main/res/layout/subitem_dashboard_grades.xml
=> Fix bugs in dashboard

app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsView.kt
=> Fix ghost account after logout not current student

app/build.gradle
=> Always include all language resources in app bundle

app/build.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableDialog.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetablewidget/TimetableWidgetFactory.kt
https://github.com/wulkanowy/sdk/pull/99
=> Mark teacher with yellow when new and old are the same

app/src/main/res/drawable/background_luckynumber_widget.xml, app/src/main/res/drawable/background_luckynumber_widget_dark.xml
=> Add transparency to lucky number widget

app/src/main/res/layout/fragment_message_tab.xml
=> Fix hiding last element in messages

app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
=> Remove seconds from timetable timer

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/io/github/wulkanowy/utils/AppInfo.kt, app/src/test/java/io/github/wulkanowy/data/db/migrations/AbstractMigrationTest.kt, app/src/test/java/io/github/wulkanowy/data/db/migrations/Migration35Test.kt, app/src/test/java/io/github/wulkanowy/data/repositories/StudentTest.kt
See https://github.com/szkolny-eu/szkolny-android/commit/582e2059d8887af985c7236f18eda892d0e302f4
=> Set buildTimestamp through manifest meta

app/build.gradle, app/src/main/res/layout/scrollable_header_about.xml
=> Fix about header layout to support long app names (for DEV builds)

app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt, app/src/main/res/layout/dialog_error.xml
=> Error messages content wrap in error dialog

app/src/main/res/layout/dialog_error.xml
=> Allow selecting text in error dialog

app/src/main/res/values/strings.xml, app/src/main/res/xml/scheme_preferences_notifications.xml
=> Notifications settings reorganize and strings update

app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt
=> Add sorting to dashboard homework and grades

app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/MessageFragment.kt, app/src/main/res/layout/fragment_school.xml
=> School and teachers UI fixes

app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolView.kt, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/strings.xml
=> Login improvements

app/build.gradle
https://android-review.googlesource.com/c/platform/frameworks/support/+/1211984
Fixes #1673
=> Update viewpager2 library to fix duplicated menu bug

app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
=> When replying to a message use `Re` instead of `RE`

app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
=> Fix exception in TimetableAdapter

app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt, app/src/main/java/io/github/wulkanowy/services/piggyback/VulcanNotificationListenerService.kt, app/src/main/res/values/preferences_defaults.xml, app/src/main/res/values/preferences_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/scheme_preferences_notifications.xml
=> Add option to remove notifications captured from vulcan.hebe

app/src/play/java/io/github/wulkanowy/services/messaging/AppMessagingService.kt
=> Fix play flavor build

app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewGradeNotification.kt, app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/mock/gradeDetails.kt
=> Display comment after entry in grade notifications

app/build.gradle, app/src/main/java/io/github/wulkanowy/services/sync/notifications/NewSchoolAnnouncementNotification.kt, app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/mock/schoolAnnouncement.kt
=> Strip html from school announcements notifications

app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt, app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardView.kt, app/src/main/java/io/github/wulkanowy/utils/ExceptionExtension.kt, app/src/main/java/io/github/wulkanowy/utils/ResourcesExtension.kt, app/src/main/res/values/strings.xml
=> Add a custom error message for ssl errors due to invalid clock setting

app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamDialog.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsDialog.kt
=> Fix blank description in exam

app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt, app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
=> Fix calc vulcan average in second semester

app/src/main/java/io/github/wulkanowy/ui/modules/exam/ExamDialog.kt, app/src/main/res/layout/dialog_exam.xml
=> Add exam date field to exam details dialog

app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
=> Display timetable header as HTML on dashboard tile

app/src/main/java/io/github/wulkanowy/data/enums/GradeSortingMode.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryPresenter.kt, app/src/main/res/values/preferences_values.xml
=> Add grade sorting by average

app/build.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt
=> Fix case sensitive domain checker

app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt
=> Fix date in attendance and timetable when day is changing

app/src/main/res/layout/fragment_student_info.xml, app/src/main/res/layout/item_student_info.xml
=> Fix multiline address in student info

app/src/main/res/layout/fragment_note.xml, app/src/main/res/layout/item_note.xml
=> Fix jumping points in notes on refresh

app/schemas/io.github.wulkanowy.data.db.AppDatabase/49.json, app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt, app/src/main/java/io/github/wulkanowy/data/db/dao/SchoolAnnouncementDao.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/SchoolAnnouncement.kt, app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration49.kt, app/src/main/java/io/github/wulkanowy/data/mappers/DirectorInformationMapper.kt, app/src/main/java/io/github/wulkanowy/data/repositories/SchoolAnnouncementRepository.kt, app/src/main/java/io/github/wulkanowy/services/sync/works/SchoolAnnouncementWork.kt, app/src/main/java/io/github/wulkanowy/ui/modules/debug/notification/mock/schoolAnnouncement.kt
=> Fix doubled and no announcements

app/src/main/java/io/github/wulkanowy/data/repositories/ReportingUnitRepository.kt
=> Add auto refresh to reporting units

.github/workflows/deploy-store.yml, .github/workflows/deploy-test.yml, .github/workflows/test.yml, app/build.gradle, build.gradle
=> Update workflow dependency

README.de.md
=> Fix typo in README DE.md

app/build.gradle, app/src/main/java/io/github/wulkanowy/data/db/dao/MailboxDao.kt, app/src/main/java/io/github/wulkanowy/data/repositories/MailboxRepository.kt, app/src/test/java/io/github/wulkanowy/data/repositories/MailboxRepositoryTest.kt
Sądząc po zgłoszeniach widać, że z jakiegoś powodu imiona uczniów są w niektórych przypadkach zakończone jedną spacją
=> Fix selecting student mailbox based on studentName field

app/build.gradle, app/src/main/java/io/github/wulkanowy/data/repositories/GradeStatisticsRepository.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/summary/GradeSummaryAdapter.kt, app/src/main/java/io/github/wulkanowy/utils/GradeExtension.kt
=> Fix student average calculation error in grade statistics

app/src/main/res/menu/action_menu_message_preview.xml
=> Reorder action buttons on the message preview screen to hide the forward button in overflow menu

app/src/main/res/layout/dialog_grade.xml
=> Fix grade weight text truncation in grade dialog with large font set

app/src/fdroid/java/io/github/wulkanowy/utils/AnalyticsHelper.kt, app/src/hms/java/io/github/wulkanowy/utils/AnalyticsHelper.kt, app/src/hms/java/io/github/wulkanowy/utils/CrashLogUtils.kt, app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt, app/src/main/java/io/github/wulkanowy/ui/base/ErrorDialog.kt, app/src/main/java/io/github/wulkanowy/ui/modules/about/AboutFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolFragment.kt, app/src/main/res/values/strings.xml, app/src/play/java/io/github/wulkanowy/utils/AnalyticsHelper.kt, app/src/play/java/io/github/wulkanowy/utils/CrashlyticsUtils.kt
=> Add installation id to crashlytics and bug report emails

app/build.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt, app/src/main/res/drawable/ic_circle.xml, app/src/main/res/layout/item_message.xml
=> Use text color, font face and red dot to differentiate unread messages 

app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsPresenter.kt, app/src/play/java/io/github/wulkanowy/utils/AdsHelper.kt
=> Fix unexpected error in support ad when no internet

README.cs.md, README.de.md, README.en.md, README.md, README.sk.md
=> Add info about optional ads in README

app/src/main/java/io/github/wulkanowy/data/mappers/MessageMapper.kt, app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardItem.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/adapters/DashboardAdapter.kt, app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt, app/src/main/res/drawable/ic_error_filled.xml, app/src/main/res/layout/item_dashboard_horizontal_group.xml
| All failed | One failed  | Two failed | All succeed |
|---|---|---|---|
| ![](https://i.imgur.com/5FYnwda.jpg)   | ![](https://i.imgur.com/8VeJOOu.jpg) | ![](https://i.imgur.com/AYlJWKy.jpg) | ![](https://i.imgur.com/k0GBA9U.jpg)
=> Improve error handling in horizontal tile on dashboard 

app/src/main/java/io/github/wulkanowy/ui/modules/account/AccountFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/account/accountdetails/AccountDetailsFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/debug/logviewer/LogViewerFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/studentinfo/StudentInfoFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt
https://discord.com/channels/390889354199040011/558394066505826304/1047909595445723250
=> Suppress menu deprecations

app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
Fixes #2056
https://discord.com/channels/390889354199040011/558394066505826304/1049313865411870801
=> Fix typo in excuse message subject

app/src/main/java/io/github/wulkanowy/data/mappers/MessageMapper.kt, app/src/main/java/io/github/wulkanowy/domain/messages/GetMailboxByStudentUseCase.kt, app/src/test/java/io/github/wulkanowy/domain/GetMailboxByStudentUseCaseTest.kt
=> Automatically show current student mailbox only when there is only one mailbox available

app/build.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/schoolannouncement/SchoolAnnouncementDialog.kt, app/src/main/java/io/github/wulkanowy/utils/StringExtension.kt
=> Fix html entities parsing in school announcements

app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt, app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
=> Fix NPE when trying to remove a message from mailbox that doesn't match any student

app/src/main/res/layout/fragment_account_details.xml, app/src/main/res/layout/item_dashboard_account.xml
=> Fix school name in dashboard and student details

app/build.gradle, app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
Fixes #2082
Related https://github.com/wulkanowy/sdk/commit/6a3e04f
=> Fix marking message as read

app/src/main/java/io/github/wulkanowy/utils/BundleExtension.kt
https://console.firebase.google.com/u/0/project/wulkanowy-d993c/crashlytics/app/android:io.github.wulkanowy/issues/33bd75470892d5954318a1533f894f1d
=> Fix crash on deserialize parcelable array

app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt, app/src/main/java/io/github/wulkanowy/utils/ContextExtension.kt, app/src/main/res/layout/fragment_login_form.xml
Related #666
| Normal                               | Fields error                         | Error box                            |
|--------------------------------------|--------------------------------------|--------------------------------------|
| ![](https://i.imgur.com/86SyMXX.jpg) | ![](https://i.imgur.com/x38bb3h.jpg) | ![](https://i.imgur.com/vmdtlQc.jpg) |
=> Set error tint to password toggle icon when error occured

app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt, app/src/main/res/layout/item_grade_statistics_header.xml
Resolves #2147
| Normal                               | Large fonts 1                          | Large fonts 2               |
|--------------------------------------|--------------------------------------|--------------------------------------|
| ![](https://i.imgur.com/N9q6tPa.jpg) | ![](https://i.imgur.com/GL8xMSV.jpg) | ![](https://i.imgur.com/tWZ5jIz.jpg) |
=> Use segmented toggle buttons instead of option group in grades statistics

app/build.gradle, app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/StudentName.kt, app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt, app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt, app/src/main/java/io/github/wulkanowy/ui/base/BaseDialogFragment.kt, app/src/main/java/io/github/wulkanowy/ui/base/BaseFragment.kt, app/src/main/java/io/github/wulkanowy/ui/base/BasePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/base/BaseView.kt, app/src/main/java/io/github/wulkanowy/ui/base/ErrorHandler.kt, app/src/main/java/io/github/wulkanowy/ui/modules/auth/AuthDialog.kt, app/src/main/java/io/github/wulkanowy/ui/modules/auth/AuthPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/auth/AuthView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/main/MainActivity.kt, app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/settings/advanced/AdvancedFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/settings/appearance/AppearanceFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/settings/notifications/NotificationsFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/settings/sync/SyncFragment.kt, app/src/main/java/io/github/wulkanowy/utils/StudentExtension.kt, app/src/main/res/drawable/ic_auth_success.xml, app/src/main/res/layout/dialog_auth.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/play/java/io/github/wulkanowy/ui/modules/settings/ads/AdsFragment.kt
=> Add auth dialog

app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/adapters/DashboardAdapter.kt, app/src/main/res/values-night-v31/styles.xml, app/src/main/res/values-night/styles.xml, app/src/main/res/values-v31/styles.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
=> Fix high priority admin message color

app/proguard-rules.pro, gradle.properties
=> Add R8 rule for Wulkanowy SDK

app/build.gradle, app/schemas/io.github.wulkanowy.data.db.AppDatabase/57.json, app/src/main/java/io/github/wulkanowy/data/Resource.kt, app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt, app/src/main/java/io/github/wulkanowy/data/db/Converters.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/AdminMessage.kt, app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration57.kt, app/src/main/java/io/github/wulkanowy/data/enums/MessageType.kt, app/src/main/java/io/github/wulkanowy/data/repositories/AdminMessageRepository.kt, app/src/main/java/io/github/wulkanowy/domain/adminmessage/GetAppropriateAdminMessageUseCase.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardItemMoveCallback.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/adapters/DashboardAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/viewholders/AdminMessageViewHolder.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormView.kt, app/src/main/res/layout/fragment_login_form.xml, app/src/test/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenterTest.kt
=> Add admin messages to login screen

app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt
=> Fix password toggle icon tint after clearing error

app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverPresenter.kt, app/src/main/res/values/strings.xml
=> Fix password reset related issues

app/src/main/java/io/github/wulkanowy/data/db/dao/StudentDao.kt, app/src/main/java/io/github/wulkanowy/data/db/entities/StudentWithSemesters.kt, app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
https://developer.android.com/training/data-storage/room/relationships#multimap
=> Add missing class_id colum in JOIN clause of students with semesters

app/src/main/java/io/github/wulkanowy/ui/modules/grade/statistics/GradeStatisticsAdapter.kt
=> Points statistics improvements

app/src/main/java/io/github/wulkanowy/ui/modules/schoolandteachers/teacher/TeacherPresenter.kt
=> Sort teachers by name in school and teachers tab

app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceView.kt, app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableView.kt, app/src/main/res/layout/fragment_attendance.xml, app/src/main/res/layout/fragment_timetable.xml
=> Allow direct access to weekend from day navigation when there is any lesson during weekend

app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetablePresenter.kt, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da-rDK/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es-rES/strings.xml, app/src/main/res/values-it-rIT/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/preferences_defaults.xml, app/src/main/res/values/preferences_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/scheme_preferences_appearance.xml
=> Timetable timers fixes

app/build.gradle
Reverts wulkanowy/wulkanowy#2368
=> Revert "Bump com.google.android.material:material from 1.10.0 to 1.11.0"

app/src/main/AndroidManifest.xml
I added the ability to dynamically resize the application window, useful when using the application on a computer
=> Add the ability to dynamically expand the application window

app/build.gradle, app/src/main/java/io/github/wulkanowy/ui/modules/login/LoginData.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/advanced/LoginAdvancedPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/form/LoginFormPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/recover/LoginRecoverPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectFragment.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenter.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/support/LoginSupportDialog.kt, app/src/main/java/io/github/wulkanowy/ui/modules/login/symbol/LoginSymbolPresenter.kt, app/src/main/res/values/api_hosts.xml, app/src/test/java/io/github/wulkanowy/TestEnityCreator.kt, app/src/test/java/io/github/wulkanowy/ui/modules/login/studentselect/LoginStudentSelectPresenterTest.kt
=>  Change default symbol for standard register variant 

app/build.gradle
Reverts wulkanowy/wulkanowy#2408
Resolves #2418
=> Revert "Bump com.google.android.ump:user-messaging-platform from 2.1.0 to 2.2.0"

app/src/main/res/layout/item_timetable.xml, app/src/main/res/layout/subitem_dashboard_small_grade.xml
Fix regression from #2435
https://discord.com/channels/390889354199040011/487672117920399390/1211628395558084718
=> Fix timetable items layout

app/src/main/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProvider.kt, app/src/test/java/io/github/wulkanowy/ui/modules/grade/GradeAverageProviderTest.kt
=> Fix calculating average with optional arithmetic average on and no grade with average in second semester

app/src/main/java/io/github/wulkanowy/ui/base/BaseActivity.kt, app/src/main/java/io/github/wulkanowy/utils/ExceptionExtension.kt, app/src/main/res/values/strings.xml
=>  Improve invalid password message 

app/src/main/java/io/github/wulkanowy/data/DataModule.kt, app/src/main/java/io/github/wulkanowy/ui/modules/captcha/CaptchaDialog.kt, app/src/main/java/io/github/wulkanowy/utils/WebkitCookieManagerProxy.kt, app/src/main/res/layout/dialog_captcha.xml, app/src/main/res/values/strings.xml
=> Add a message explaining the reason for the captcha to the captcha dialog

app/src/main/java/io/github/wulkanowy/data/Resource.kt, app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt, app/src/main/java/io/github/wulkanowy/domain/attendance/GetAttendanceCalculatorDataUseCase.kt, app/src/main/java/io/github/wulkanowy/ui/modules/attendance/calculator/AttendanceCalculatorAdapter.kt, app/src/main/res/values/preferences_defaults.xml, app/src/main/res/values/preferences_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/scheme_preferences_appearance.xml
=> Handle subjects with no attendances in attendance calculator better

app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceAdapter.kt, app/src/main/res/values/colors.xml
=> Fix lateness color in attendance

app/play-publish-lint.sh, app/src/main/java/io/github/wulkanowy/data/Resource.kt
Also normalize line endings in lint check
=> Add docs to Resource, changing networkBoundResource generics naming
